name: dart_sip_ua_example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  device_info_plus: ^11.2.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_callkit_incoming: ^2.5.0
  flutter_local_notifications: ^18.0.1
  flutter_webrtc: ^0.12.4
  logger: ^2.4.0
  no_context_navigation: ^3.0.0
  permission_handler: ^11.1.0
  provider: 6.1.2
  shared_preferences: ^2.2.0
  sip_ua:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1
flutter:
  uses-material-design: true
